### ISSUE TITLE
Collaboration agreement link pointing to the wrong file

### ISSUE THREAD

**Issue by eggls6** [iausathub/score#21]
Anthony Mallama pointed out that the link to the collaboration agreement is pointing to the membership application form. I think the membership agreement is [here](https://docs.google.com/forms/d/e/1FAIpQLSe6w5rZhxvF0ozGe1dMssLTolua1Apq1_QjJ8aLWprGUGQGog/viewform).

**Comment by mpeel** [comment]
the better link to use would be https://drive.google.com/file/d/1tPChesKIz9VSQshb3oPcM1J71xpayS9v/view - since that's what the new membership application form links to, at https://docs.google.com/forms/d/e/1FAIpQLSdFL6JviMl4-W3xIlWrZACFOWV-6B8SVptPpxTYtLZOXgUHmg/viewform
