### ISSUE TITLE
Cannot Add Observation 'Satellite with this ID not visible at this time and location'

### ISSUE THREAD

**Issue by harryk333** [iausathub/score#23]
Attempting to add a single observation or upload a CSV yields an error: 'Satellite with this ID not visible at this time and location'

The example observations I am attempting to add are from 2022, so this may simply be an issue that SatChecker does not have TLE data this old. Or something else is going wrong. The CSV I am using is attached. 
[obs_example.csv](https://github.com/iausathub/score/files/14972168/obs_example.csv)

**Comment by mdadighat** [comment]
Yeah, this is from the data being older than the oldest TLE we have - it puts the satellite altitude at -54 degrees which fails the check. I'm going to update this to skip the check if the date from the observation is older than our oldest TLE, which should account for things as we add archival data.
